/**
 * Application credentials
 *
 * Reads DATABASE_URL (and related platform env) from process.env.
 * On local dev, setup wizard can write to .env + set process.env in-memory.
 * On Vercel, env vars are set via the dashboard — writes are not supported.
 *
 * SERVER-ONLY: uses Node.js fs — never import in client code.
 */

import 'server-only';

import fs from 'fs/promises';
import path from 'path';
import type { DatabaseConfig } from '@/types';

const ENV_FILE = path.join(process.cwd(), '.env');
const IS_VERCEL = process.env.VERCEL === '1';

/**
 * Build DatabaseConfig from env.
 * Prefers DATABASE_URL; falls back to legacy SUPABASE_CONNECTION_URL + password
 * so existing installs keep working during migration.
 */
function getDatabaseConfigFromEnv(): DatabaseConfig | null {
  const databaseUrl = process.env.DATABASE_URL;
  if (databaseUrl) {
    return {
      databaseUrl,
      authSecret: process.env.BETTER_AUTH_SECRET || process.env.PAGE_AUTH_SECRET,
      storageDriver: (process.env.STORAGE_DRIVER as 'local' | 's3') || 'local',
      redisUrl: process.env.REDIS_URL,
      defaultTenantId: process.env.DEFAULT_TENANT_ID,
    };
  }

  // Legacy Supabase connection string → synthesize DATABASE_URL
  const connectionUrl = process.env.SUPABASE_CONNECTION_URL;
  const dbPassword = process.env.SUPABASE_DB_PASSWORD;
  if (connectionUrl && dbPassword) {
    const resolved = connectionUrl.replace('[YOUR-PASSWORD]', encodeURIComponent(dbPassword));
    return {
      databaseUrl: resolved,
      authSecret: process.env.BETTER_AUTH_SECRET || process.env.SUPABASE_SECRET_KEY || process.env.PAGE_AUTH_SECRET,
      storageDriver: (process.env.STORAGE_DRIVER as 'local' | 's3') || 'local',
      redisUrl: process.env.REDIS_URL,
      defaultTenantId: process.env.DEFAULT_TENANT_ID,
    };
  }

  return null;
}

/**
 * Get a value from storage (reads from environment variables).
 */
export async function get<T = unknown>(key: string): Promise<T | null> {
  if (key === 'database_config' || key === 'supabase_config') {
    return getDatabaseConfigFromEnv() as T;
  }
  return null;
}

/**
 * Set a value in storage.
 * Writes to .env and sets process.env in-memory for immediate availability.
 * On Vercel, throws — env vars must be set via the dashboard.
 */
export async function set(key: string, value: unknown): Promise<void> {
  if (IS_VERCEL) {
    throw new Error(
      'Cannot write to file system on Vercel. Please set environment variables instead:\n' +
      '1. Go to Vercel Dashboard → Project Settings → Environment Variables\n' +
      '2. Add: DATABASE_URL, BETTER_AUTH_SECRET, REDIS_URL, STORAGE_DRIVER\n' +
      '3. Redeploy your application'
    );
  }

  if (key === 'database_config' || key === 'supabase_config') {
    const config = value as DatabaseConfig;

    process.env.DATABASE_URL = config.databaseUrl;
    if (config.authSecret) {
      process.env.BETTER_AUTH_SECRET = config.authSecret;
    }
    if (config.storageDriver) {
      process.env.STORAGE_DRIVER = config.storageDriver;
    }
    if (config.redisUrl) {
      process.env.REDIS_URL = config.redisUrl;
    }
    if (config.defaultTenantId) {
      process.env.DEFAULT_TENANT_ID = config.defaultTenantId;
    }

    await writeEnvFile(config);
  }
}

/**
 * Delete database config from env / .env.
 */
export async function del(key: string): Promise<void> {
  if (key === 'database_config' || key === 'supabase_config') {
    delete process.env.DATABASE_URL;
    delete process.env.BETTER_AUTH_SECRET;
    delete process.env.STORAGE_DRIVER;
    delete process.env.REDIS_URL;
    delete process.env.DEFAULT_TENANT_ID;
    // Keep legacy keys cleared too
    delete process.env.SUPABASE_PUBLISHABLE_KEY;
    delete process.env.SUPABASE_SECRET_KEY;
    delete process.env.SUPABASE_CONNECTION_URL;
    delete process.env.SUPABASE_DB_PASSWORD;
    delete process.env.SUPABASE_URL;

    try {
      await removeDbVarsFromEnv();
    } catch {
      // File may not exist
    }
  }
}

/**
 * Check if database credentials are configured.
 */
export async function exists(): Promise<boolean> {
  return getDatabaseConfigFromEnv() !== null;
}

const DB_ENV_KEYS = [
  'DATABASE_URL',
  'BETTER_AUTH_SECRET',
  'STORAGE_DRIVER',
  'STORAGE_LOCAL_PATH',
  'STORAGE_PUBLIC_BASE_URL',
  'REDIS_URL',
  'DEFAULT_TENANT_ID',
  'S3_BUCKET',
  'S3_REGION',
  'S3_ENDPOINT',
  'S3_ACCESS_KEY_ID',
  'S3_SECRET_ACCESS_KEY',
  'S3_FORCE_PATH_STYLE',
  // legacy
  'SUPABASE_PUBLISHABLE_KEY',
  'SUPABASE_SECRET_KEY',
  'SUPABASE_CONNECTION_URL',
  'SUPABASE_DB_PASSWORD',
  'SUPABASE_URL',
];

async function writeEnvFile(config: DatabaseConfig): Promise<void> {
  let existing = '';
  try {
    existing = await fs.readFile(ENV_FILE, 'utf-8');
  } catch {
    // File doesn't exist yet
  }

  const filtered = existing
    .split('\n')
    .filter((line) => {
      if (line === '# Auto-generated by Ycode setup wizard') return false;
      return !DB_ENV_KEYS.some((key) => line.startsWith(`${key}=`));
    })
    .join('\n')
    .trimEnd();

  const lines = [
    '# Auto-generated by Ycode setup wizard',
    `DATABASE_URL="${config.databaseUrl}"`,
  ];

  if (config.authSecret) {
    lines.push(`BETTER_AUTH_SECRET="${config.authSecret}"`);
  }
  if (config.storageDriver) {
    lines.push(`STORAGE_DRIVER="${config.storageDriver}"`);
  }
  if (config.redisUrl) {
    lines.push(`REDIS_URL="${config.redisUrl}"`);
  }
  if (config.defaultTenantId) {
    lines.push(`DEFAULT_TENANT_ID="${config.defaultTenantId}"`);
  }

  const block = lines.join('\n');
  const content = filtered ? `${filtered}\n${block}\n` : `${block}\n`;
  await fs.writeFile(ENV_FILE, content, 'utf-8');
}

async function removeDbVarsFromEnv(): Promise<void> {
  const existing = await fs.readFile(ENV_FILE, 'utf-8');
  const filtered = existing
    .split('\n')
    .filter((line) => {
      if (line === '# Auto-generated by Ycode setup wizard') return false;
      return !DB_ENV_KEYS.some((key) => line.startsWith(`${key}=`));
    })
    .join('\n')
    .trimEnd();

  await fs.writeFile(ENV_FILE, filtered ? `${filtered}\n` : '', 'utf-8');
}

export const credentials = {
  get,
  set,
  del,
  exists,
};
